//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsConsumirNet.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WindowsFormsConsumirNet.ServiceReference1.HelloWorldResponse HelloWorld(WindowsFormsConsumirNet.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsConsumirNet.ServiceReference1.HelloWorldResponse> HelloWorldAsync(WindowsFormsConsumirNet.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ci del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenermaterias", ReplyAction="*")]
        WindowsFormsConsumirNet.ServiceReference1.obtenermateriasResponse obtenermaterias(WindowsFormsConsumirNet.ServiceReference1.obtenermateriasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenermaterias", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsConsumirNet.ServiceReference1.obtenermateriasResponse> obtenermateriasAsync(WindowsFormsConsumirNet.ServiceReference1.obtenermateriasRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsConsumirNet.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WindowsFormsConsumirNet.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsConsumirNet.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WindowsFormsConsumirNet.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenermateriasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenermaterias", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsConsumirNet.ServiceReference1.obtenermateriasRequestBody Body;
        
        public obtenermateriasRequest() {
        }
        
        public obtenermateriasRequest(WindowsFormsConsumirNet.ServiceReference1.obtenermateriasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenermateriasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ci;
        
        public obtenermateriasRequestBody() {
        }
        
        public obtenermateriasRequestBody(string ci) {
            this.ci = ci;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenermateriasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenermateriasResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsConsumirNet.ServiceReference1.obtenermateriasResponseBody Body;
        
        public obtenermateriasResponse() {
        }
        
        public obtenermateriasResponse(WindowsFormsConsumirNet.ServiceReference1.obtenermateriasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenermateriasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string obtenermateriasResult;
        
        public obtenermateriasResponseBody() {
        }
        
        public obtenermateriasResponseBody(string obtenermateriasResult) {
            this.obtenermateriasResult = obtenermateriasResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WindowsFormsConsumirNet.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WindowsFormsConsumirNet.ServiceReference1.WebService1Soap>, WindowsFormsConsumirNet.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsConsumirNet.ServiceReference1.HelloWorldResponse WindowsFormsConsumirNet.ServiceReference1.WebService1Soap.HelloWorld(WindowsFormsConsumirNet.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WindowsFormsConsumirNet.ServiceReference1.HelloWorldRequest inValue = new WindowsFormsConsumirNet.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WindowsFormsConsumirNet.ServiceReference1.HelloWorldRequestBody();
            WindowsFormsConsumirNet.ServiceReference1.HelloWorldResponse retVal = ((WindowsFormsConsumirNet.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsConsumirNet.ServiceReference1.HelloWorldResponse> WindowsFormsConsumirNet.ServiceReference1.WebService1Soap.HelloWorldAsync(WindowsFormsConsumirNet.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsConsumirNet.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            WindowsFormsConsumirNet.ServiceReference1.HelloWorldRequest inValue = new WindowsFormsConsumirNet.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WindowsFormsConsumirNet.ServiceReference1.HelloWorldRequestBody();
            return ((WindowsFormsConsumirNet.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsConsumirNet.ServiceReference1.obtenermateriasResponse WindowsFormsConsumirNet.ServiceReference1.WebService1Soap.obtenermaterias(WindowsFormsConsumirNet.ServiceReference1.obtenermateriasRequest request) {
            return base.Channel.obtenermaterias(request);
        }
        
        public string obtenermaterias(string ci) {
            WindowsFormsConsumirNet.ServiceReference1.obtenermateriasRequest inValue = new WindowsFormsConsumirNet.ServiceReference1.obtenermateriasRequest();
            inValue.Body = new WindowsFormsConsumirNet.ServiceReference1.obtenermateriasRequestBody();
            inValue.Body.ci = ci;
            WindowsFormsConsumirNet.ServiceReference1.obtenermateriasResponse retVal = ((WindowsFormsConsumirNet.ServiceReference1.WebService1Soap)(this)).obtenermaterias(inValue);
            return retVal.Body.obtenermateriasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsConsumirNet.ServiceReference1.obtenermateriasResponse> WindowsFormsConsumirNet.ServiceReference1.WebService1Soap.obtenermateriasAsync(WindowsFormsConsumirNet.ServiceReference1.obtenermateriasRequest request) {
            return base.Channel.obtenermateriasAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsConsumirNet.ServiceReference1.obtenermateriasResponse> obtenermateriasAsync(string ci) {
            WindowsFormsConsumirNet.ServiceReference1.obtenermateriasRequest inValue = new WindowsFormsConsumirNet.ServiceReference1.obtenermateriasRequest();
            inValue.Body = new WindowsFormsConsumirNet.ServiceReference1.obtenermateriasRequestBody();
            inValue.Body.ci = ci;
            return ((WindowsFormsConsumirNet.ServiceReference1.WebService1Soap)(this)).obtenermateriasAsync(inValue);
        }
    }
}
